### ISSUE TITLE
Crash logging onto server

### ISSUE THREAD

**Issue by b0b4444** [TalonFox/EnhancedWeather#19]
**Describe the bug**
I have a big modpack. Suddenly, when I log in my client crashes. When I do /enhancedweather killallOverworld on the server console, the server crashes. 

**To Reproduce**
1. Install all mods
2. Run server
3. Log in on client
4. Run Enhanced Weather Commands on server

**Expected behavior**
Logging in without issue (as I have in the past)

**Screenshots**

**System Information:**
 - OS: macOS (Linux on the server)
 - Minecraft Version: 1.19.2
 - Fabric/Quilt Loader Version: 0.14.19
 - Fabric API Version: Fabric API 0.76.0+1.19.2
 - EnhancedWeather Version: 1.0 Beta-5
 - Loaded mods: (See crash log)

**Additional context**
Opening of the crash log (which is attached):
Description: Ticking entity

java.lang.NullPointerException: Cannot invoke "sh.talonfox.enhancedweather.weather.ServersideManager.getClosestCloud(net.minecraft.class_243, double, boolean, boolean, boolean, boolean, int)" because "sh.talonfox.enhancedweather.EnhancedWeather.SERVER_WEATHER" is null
[crash-2023-05-06_00.11.20-client.txt](https://github.com/TalonFox/EnhancedWeather/files/11411261/crash-2023-05-06_00.11.20-client.txt)

**Comment by PixelatedBruh** [comment]
I will add on by saying i have got this exact same issue on my server my log is slightly different but the issue seams the same
[crash-2023-05-05_22.10.05-client.txt](https://github.com/TalonFox/EnhancedWeather/files/11411337/crash-2023-05-05_22.10.05-client.txt)

**Comment by TalonFox** [comment]
Hello @bob4444, thank you for reporting this. At the moment, these commands only work on singleplayer mode. I will try to fix this in the near future. Thank you for reporting this.

**Comment by b0b4444** [comment]
Any update on this? Was it resolved in the 1.20 update? If so, will you be updating the other game versions as well?

**Comment by TalonFox** [comment]
I haven't fixed this yet, I'm currently working on other stuff and never got to doing that, though it is in my list of things to fix eventually. Technically the commands were meant for debugging purposes and weren't meant to be ran on a decdicated server, however I will try to fix this soon. Also unfortunately, this fix won't be backported to older versions, it will only be available for the latest version of Minecraft when it does get fixed, it just makes development easier.

**Comment by TalonFox** [comment]
These issues have now been fixed on the latest version of Enhanced Weather ;3
