### ISSUE TITLE
Bug: Snow Layers Not Generating

### ISSUE THREAD

**Issue by RelentlessTitanic** [TalonFox/EnhancedWeather#23]
Snow layers do not generate in overworld when using the Enhanced Weather mod for Fabric 1.20.1.
When generating new chunks in a snowy plains biome or a snowy taiga biome, snow layers do not generate causing the snowy plains just to look like a more depressing version of regular plains and causing the snowy taiga to look almost identical to a regular taiga because snow layers do not generate.

![2023-07-28_12 08 12](https://github.com/TalonFox/EnhancedWeather/assets/140217541/54665f5c-15ef-4ece-94db-56228c2fdae5)

**System Information:**
 - OS: Windows 11
 - Minecraft Version: 1.20.1
 - Fabric/Quilt Loader Version: Fabric Loader 0.14.21-1.20.1
 - Fabric API Version: 0.83.1+1.20.1
 - EnhancedWeather Version: v1.0-Beta5.3.jar
 - Loaded mods: 
![image_2023-07-28_121501893](https://github.com/TalonFox/EnhancedWeather/assets/140217541/8f589623-fd30-46a1-a7c8-98b2d689f045)
![image_2023-07-28_121527858](https://github.com/TalonFox/EnhancedWeather/assets/140217541/aad3d1b3-f118-4126-91e4-f70435c61a19)
![image_2023-07-28_121547432](https://github.com/TalonFox/EnhancedWeather/assets/140217541/9801d0c2-eaef-46d7-ba92-2558efefec89)
![image_2023-07-28_121641875](https://github.com/TalonFox/EnhancedWeather/assets/140217541/1e777c60-7cc6-4a3d-9863-58dd3a7e2592)
(mods are in the images)

**Comment by TalonFox** [comment]
![2023-07-28_14 43 20](https://github.com/TalonFox/EnhancedWeather/assets/105325988/1e23576a-a245-462e-9472-3fb9c9942d02)
I can verify this, I'm going to start work on fixing this. Thank you for the report!

**Comment by TalonFox** [comment]
@RelentlessTitanic This issue has now been fixed in the latest commit, I'll release the JAR onto Modrinth shortly.

**Comment by RelentlessTitanic** [comment]
> @RelentlessTitanic This issue has now been fixed in the latest commit, I'll release the JAR onto Modrinth shortly.

Okay, thank you so much. Cool mod by the way!

**Comment by TalonFox** [comment]
Thanks :3
