### ISSUE TITLE
add power flash to the mod  

### ISSUE THREAD

**Issue by Mungydungy** [TalonFox/EnhancedWeather#26]
add power flash to the mod

**Comment by TalonFox** [comment]
Not exactly sure what that is, do you think you could give more context and maybe provide examples?

**Comment by TalonFox** [comment]
ohhh i see

**Comment by AlexTheSuprWolf** [comment]
don't really see how these would be realistically implemented. Power flashes are cause by Tornadoes going over powerlines and other electrical equipment. Minecraft doesn't have powerlines. maybe a red flash if it passed over active redstone? but other than that, this doesn't really make any sense to add.

**Comment by TalonFox** [comment]
I agree with AlexTheSuprWolf on this one, this doesn't really fit with the mod in general.
